---
# tasks file for ams.ams_lab.win_infra

- name: Install and Configure Microsoft Active Directory
  tags: adds
  block:
    - name: Install Windows Features required for an Active Directory Domain
      ansible.windows.win_feature:
        name: "{{ item }}"
        include_management_tools: true
        include_sub_features: true
      loop: "{{ win_infra_features_ad }}"

    - name: I want to be a Domain Controller when I grow up!
      microsoft.ad.domain:
        dns_domain_name: "{{ win_infra['ad_domain_name'] }}"
        domain_netbios_name: "{{ win_infra['ad_domain_name'].split('.')[0] | upper }}"
        install_dns: false
        reboot: true
        safe_mode_password: 'New123Pass!!'

- name: Install DNS tools
  ansible.windows.win_feature:
    name: "{{ item }}"
    include_sub_features: true
    include_management_tools: true
  loop: "{{ win_infra_features_dns }}"
  tags: dns

- name: Install and Configure Microsoft Active Directory Certificate Services
  tags: adcs
  block:
    - name: Installing CA Features
      ansible.windows.win_feature:
        name: "{{ item }}"
        include_sub_features: true
        include_management_tools: true
      loop: "{{ win_infra_features_ca }}"

    - name: Installing CA PowerShell modules
      ansible.windows.win_powershell:
        script: |
          Install-PackageProvider -Name NuGet -Force
          Install-Module ADCSDeployment

    - name: Installing Certificate Authority
      ansible.windows.win_powershell:
        script: |
          Import-Module ADCSDeployment
          Install-AdcsCertificationAuthority -CAType StandaloneRootCa -Force
