---
collections:
  - name: ams.ams_lab
    version: 1.0.0
    source: /home/dkettman/ansible/ams-ams_lab-1.0.0.tar.gz
    type: file
  - name: ansible.windows
    version: 3.2.0
  - name: community.general
    version: 11.4.0
  - name: microsoft.ad
    version: 1.9.2
