---
# - name: Setup Remmina Bookmarks
#   hosts: all
#   tasks:
#     - name: Create RDP-related Bookmarks
#       ansible.builtin.template:
#         src: remmina_rdp.j2
#         dest: ~/.local/share/remmina/
#         mode: '0644'

- name: Build Remmina Connection files
  hosts: all
  tasks:
    - name: Get Incus info
      ansible.builtin.command: "incus list ipv4={{ ansible_host }} -f json"
      register: incus_info
      changed_when: false
      delegate_to: localhost

    - name: Print Incus Info
      ansible.builtin.set_fact:
        cacheable: true
        incus_config: "{{ incus_info.stdout | from_json }}"

    # - name: Print Facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

# yamllint disable rule:line-length
- name: Get Keyring Secret
  hosts: all
  tasks:
    - name: Create RDP Template for Remmina
      # ansible.builtin.debug:
      #   msg: /home/dkettman/.local/share/remmina/{{ lab_name + '_rdp_' + ansible_facts.incus_config[0].name + '_' + ansible_host | replace('.', '-') + '.remmina' }}
      ansible.builtin.template:
        src: ./remmina_rdp.j2
        # dest: "/home/dkettman/.local/share/remmina/{{ lab_name + '_rdp_' + ansible_facts.incus_config[0].name + ansible_host | replace('.','_') }}"
        dest: "./{{ lab_name + '_rdp_' + ansible_facts.incus_config[0].name + ansible_host | replace('.', '_') }}.remmina"
        mode: '0644'
      delegate_to: localhost
      when: '"Windows" in ansible_facts.distribution'
# yamllint enable rule:line-length
