#SPDXLicense-Identifier: MIT-0
---
- name: Gather some required facts for installation
  ansible.builtin.command: dpkg --print-architecture
  register: ams_vault_dpkg_arch
  changed_when: false

- name: Check if Hashicorp APT Repository is already installed
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/apt_releases_hashicorp_com.list
  register: ams_vault_hashicorp_apt_file

- name: Install the Hashicorp APT Repository
  when: not ams_vault_hashicorp_apt_file.stat.exists
  block:
    - name: Install a couple packages from APT repositories if not installed
      ansible.builtin.apt:
        pkg:
          - gpg
          - vim
          - less
          - python3-pylxd
          - jq
        update_cache: true

    - name: Check if HashiCorp GPG Key is already downloaded
      ansible.builtin.file:
        path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: file
      register: ams_vault_hcp_gpg_key_file
      ignore_errors: true

    - name: Check if gpg file already exists
      ansible.builtin.file:
        path: /tmp/hashi-apt-gpg
        state: file
      register: ams_vault_hcp_gpg_tmp_file
      ignore_errors: true

    - name: Install HashiCorp GPG Key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /tmp/hashi-apt-gpg
        mode: '0440'
      register: hcp_gpg_file
      when: ( ams_vault_hcp_gpg_key_file is failed ) and ( ams_vault_hcp_gpg_tmp_file is failed )

    - name: Import HashiCorp GPG Key
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg {{ ams_vault_hcp_gpg_tmp_file.path }}
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp APT Repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ ams_vault_dpkg_arch.stdout }} signed-by={{ ams_vault_hcp_gpg_key_file.path }}]
          https://apt.releases.hashicorp.com
          {{ ansible_facts.lsb.codename }} main
        state: present

- name: Install HashiCorp Vault
  ansible.builtin.apt:
    name: vault

- name: Create directory for Vault Data storage
  ansible.builtin.file:
    path: /opt/vault/vault-data
    state: directory
    mode: "0644"

# This will need to be turned into a bunch of variables or something eventually...
# - name: Configure vault servers
#   ansible.builtin.template:
#     src: vault-server.hcl.j2
#     dest: /opt/vault/vault-server.hcl
#     mode: "0640"
- name: Add VAULT_ADDR and VAULT_SKIP_VERIFY to ~/.profile
  ansible.builtin.blockinfile:
    path: /root/.profile
    block: |
      export VAULT_ADDR=https://127.0.0.1:8200
      export VAULT_SKIP_VERIFY=true
# - name: Generate OpenSSL Private Key
#   community.crypto.openssl_privatekey:
#     path: /opt/vault/vault-key.pem
#   register: vault_ssl_priv_key
# - name: Generate OpenSSL Certificate Signing Request (CSR)
#   community.crypto.openssl_csr:
#     CN: "{{ ansible_hostname }}"
#     subjectAltName: ["DNS:{{ ansible_hostname }}",
#                      "DNS:{{ ansible_hostname }}.lxd",
#                      "DNS:localhost",
#                      "IP:127.0.0.1"
#     ]
#     path: /opt/vault/vault-cert.csr
#     privatekey_path: "{{ vault_ssl_priv_key.filename }}"
#   register: vault_ssl_csr
# - name: Generate OpenSSL Certificate
#   community.crypto.x509_certificate:
#     path: /opt/vault/vault-cert.pem
#     privatekey_path: "{{ vault_ssl_priv_key.filename }}"
#     csr_path: "{{ vault_ssl_csr.filename }}"
#     provider: selfsigned
