---
- name: Gather Incus/LXD information
  hosts: all
  tasks:
    - name: Get Incus info
      ansible.builtin.command: "incus list ipv4={{ ansible_host }} -f json"
      register: incus_info
      delegate_to: localhost
      changed_when: false

    - name: Set Incus Config to f(incus_config)
      ansible.builtin.set_fact:
        cacheable: true
        incus_config: "{{ incus_info.stdout | from_json }}"

    - name: Set ComputerName to Container name
      ansible.windows.win_hostname:
        name: "{{ ansible_facts.incus_config[0].name }}"
      register: res
      when: ansible_lxd_os == "windows"

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required

- name: Setting up Windows Infrastructure
  hosts: windows
  gather_facts: true
  roles:
    - role: ams.ams_lab.win_infra
      win_infra:
        ad_domain_name: amslab.local
